[package]
name = "typst-ffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[[bin]]
name = "test-typst-ffi"
path = "src/main.rs"

[dependencies]
typst = "0.13.1"
typst-pdf = "0.13.1"
typst-utils = "0.13.1"
libc = "0.2"

[build-dependencies]
cbindgen = "0.29"
